// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSW2usqORC4LvYxw00UIymPNMjdLd0Eiw',
    appId: '1:599110020532:web:d2afeda9def3512d5e56e1',
    messagingSenderId: '599110020532',
    projectId: 'rapidcart-bdf9b',
    authDomain: 'rapidcart-bdf9b.firebaseapp.com',
    storageBucket: 'rapidcart-bdf9b.firebasestorage.app',
    measurementId: 'G-9QQ02CMDHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMtNkv7oDlv1HTeoCtGIfP01c__lhjiQ',
    appId: '1:599110020532:android:bd1ea475d1d7c6de5e56e1',
    messagingSenderId: '599110020532',
    projectId: 'rapidcart-bdf9b',
    storageBucket: 'rapidcart-bdf9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_AcGZoXasjRtAtuKPdW0JOEWKptEWNM',
    appId: '1:599110020532:ios:90a6b212b272e2955e56e1',
    messagingSenderId: '599110020532',
    projectId: 'rapidcart-bdf9b',
    storageBucket: 'rapidcart-bdf9b.firebasestorage.app',
    iosBundleId: 'com.example.rapidCart',
  );
}
